import { PTBTemplateItem } from './type';

const splitTemplateJson = {
  version: 'ptb_3',
  chain: 'sui:testnet',
  view: {
    x: 39.284210526315746,
    y: 94.42368421052632,
    zoom: 0.9421052631578948,
  },
  graph: {
    nodes: [
      {
        id: '@start',
        kind: 'Start',
        label: 'Start',
        position: { x: 71.87709497206708, y: 84 },
        ports: [{ id: 'next', direction: 'out', role: 'flow' }],
      },
      {
        id: '@end',
        kind: 'End',
        label: 'End',
        position: { x: 1031.877094972067, y: 84 },
        ports: [{ id: 'prev', direction: 'in', role: 'flow' }],
      },
      {
        id: 'cmd-splitCoins-1',
        kind: 'Command',
        label: 'SplitCoins',
        command: 'splitCoins',
        params: { ui: { amountsCount: 1 } },
        ports: [
          { id: 'prev', direction: 'in', role: 'flow' },
          { id: 'next', direction: 'out', role: 'flow' },
          {
            id: 'in_coin',
            direction: 'in',
            role: 'io',
            dataType: { kind: 'object' },
            label: 'in_coin',
          },
          {
            id: 'in_amount_0',
            direction: 'in',
            role: 'io',
            dataType: { kind: 'move_numeric', width: 'u64' },
            label: 'in_amount_0',
          },
          {
            id: 'out_coin_0',
            direction: 'out',
            role: 'io',
            dataType: { kind: 'object' },
            label: 'out_coin_0',
          },
        ],
        position: { x: 391.8770949720671, y: 84 },
      },
      {
        id: 'cmd-transferObjects-2',
        kind: 'Command',
        label: 'TransferObjects',
        command: 'transferObjects',
        params: { ui: { objectsCount: 1 } },
        ports: [
          { id: 'prev', direction: 'in', role: 'flow' },
          { id: 'next', direction: 'out', role: 'flow' },
          {
            id: 'in_recipient',
            direction: 'in',
            role: 'io',
            dataType: { kind: 'scalar', name: 'address' },
            label: 'in_recipient',
          },
          {
            id: 'in_object_0',
            direction: 'in',
            role: 'io',
            dataType: { kind: 'object' },
            label: 'in_object_0',
          },
        ],
        position: { x: 711.8770949720671, y: 84 },
      },
      {
        id: '@my_wallet',
        kind: 'Variable',
        label: 'my wallet',
        name: 'sender',
        varType: { kind: 'scalar', name: 'address' },
        ports: [
          {
            id: 'out',
            role: 'io',
            direction: 'out',
            label: 'my wallet',
            dataType: { kind: 'scalar', name: 'address' },
            typeStr: 'address',
          },
        ],
        position: { x: 391.8770949720671, y: 212 },
      },
      {
        id: '@gas',
        kind: 'Variable',
        label: 'gas',
        name: 'gas',
        varType: { kind: 'object' },
        ports: [
          {
            id: 'out',
            role: 'io',
            direction: 'out',
            label: 'gas',
            dataType: { kind: 'object' },
            typeStr: 'object',
          },
        ],
        position: { x: 71.87709497206708, y: 212 },
      },
      {
        id: 'var-9',
        kind: 'Variable',
        label: 'number',
        name: 'var',
        varType: { kind: 'scalar', name: 'number' },
        value: '1',
        ports: [
          {
            id: 'out',
            role: 'io',
            direction: 'out',
            label: 'number',
            dataType: { kind: 'scalar', name: 'number' },
            typeStr: 'number',
          },
        ],
        position: { x: 71.87709497206708, y: 328 },
      },
    ],
    edges: [
      {
        id: 'edge-3',
        kind: 'flow',
        source: '@start',
        target: 'cmd-splitCoins-1',
        sourceHandle: 'next',
        targetHandle: 'prev',
      },
      {
        id: 'edge-4',
        kind: 'flow',
        source: 'cmd-splitCoins-1',
        target: 'cmd-transferObjects-2',
        sourceHandle: 'next',
        targetHandle: 'prev',
      },
      {
        id: 'edge-5',
        kind: 'flow',
        source: 'cmd-transferObjects-2',
        target: '@end',
        sourceHandle: 'next',
        targetHandle: 'prev',
      },
      {
        id: 'edge-6',
        kind: 'io',
        source: '@my_wallet',
        target: 'cmd-transferObjects-2',
        sourceHandle: 'out:address',
        targetHandle: 'in_recipient:address',
      },
      {
        id: 'edge-7',
        kind: 'io',
        source: '@gas',
        target: 'cmd-splitCoins-1',
        sourceHandle: 'out:object',
        targetHandle: 'in_coin:object',
      },
      {
        id: 'edge-8',
        kind: 'io',
        source: 'cmd-splitCoins-1',
        target: 'cmd-transferObjects-2',
        sourceHandle: 'out_coin_0:object',
        targetHandle: 'in_object_0:object',
      },
      {
        id: 'edge-10',
        kind: 'io',
        source: 'var-9',
        target: 'cmd-splitCoins-1',
        sourceHandle: 'out:number',
        targetHandle: 'in_amount_0:number',
        cast: { to: 'u64' },
      },
    ],
  },
  modules: {},
  objects: {},
};

export const PTBTemplate_split: PTBTemplateItem = {
  id: 'split',
  label: 'Split Template',
  description: 'Sample split pipeline',
  defaultName: 'split.ptb',
  detail: 'Split a Coin into parts (SplitCoins).',
  // eslint-disable-next-line no-restricted-syntax
  file: () => JSON.stringify(splitTemplateJson, null, 2),
};
