import { PTBTemplateItem } from './type';

const mergeTemplateJson = {
  version: 'ptb_3',
  chain: 'sui:testnet',
  view: {
    x: -334.71578947368425,
    y: 309.6447368421052,
    zoom: 0.9421052631578948,
  },
  graph: {
    nodes: [
      {
        id: '@start',
        kind: 'Start',
        label: 'Start',
        position: { x: 468.86033519553075, y: -144.44692737430162 },
        ports: [{ id: 'next', direction: 'out', role: 'flow' }],
      },
      {
        id: '@end',
        kind: 'End',
        label: 'End',
        position: { x: 1428.8603351955308, y: -144.44692737430162 },
        ports: [{ id: 'prev', direction: 'in', role: 'flow' }],
      },
      {
        id: 'cmd-splitCoins-1',
        kind: 'Command',
        label: 'SplitCoins',
        command: 'splitCoins',
        params: { ui: { amountsCount: 1 } },
        ports: [
          { id: 'prev', direction: 'in', role: 'flow' },
          { id: 'next', direction: 'out', role: 'flow' },
          {
            id: 'in_coin',
            direction: 'in',
            role: 'io',
            dataType: { kind: 'object' },
            label: 'in_coin',
          },
          {
            id: 'in_amount_0',
            direction: 'in',
            role: 'io',
            dataType: { kind: 'move_numeric', width: 'u64' },
            label: 'in_amount_0',
          },
          {
            id: 'out_coin_0',
            direction: 'out',
            role: 'io',
            dataType: { kind: 'object' },
            label: 'out_coin_0',
          },
        ],
        position: { x: 788.8603351955308, y: -144.44692737430162 },
      },
      {
        id: '@gas',
        kind: 'Variable',
        label: 'gas',
        name: 'gas',
        varType: { kind: 'object' },
        ports: [
          {
            id: 'out',
            role: 'io',
            direction: 'out',
            label: 'gas',
            dataType: { kind: 'object' },
            typeStr: 'object',
          },
        ],
        position: { x: 468.86033519553075, y: -16.446927374301623 },
      },
      {
        id: 'var-9',
        kind: 'Variable',
        label: 'number',
        name: 'var',
        varType: { kind: 'scalar', name: 'number' },
        value: '1',
        ports: [
          {
            id: 'out',
            role: 'io',
            direction: 'out',
            label: 'number',
            dataType: { kind: 'scalar', name: 'number' },
            typeStr: 'number',
          },
        ],
        position: { x: 468.86033519553075, y: 99.55307262569838 },
      },
      {
        id: 'cmd-mergeCoins-11',
        kind: 'Command',
        label: 'MergeCoins',
        command: 'mergeCoins',
        params: { ui: { sourcesCount: 1 } },
        ports: [
          { id: 'prev', direction: 'in', role: 'flow' },
          { id: 'next', direction: 'out', role: 'flow' },
          {
            id: 'in_dest',
            direction: 'in',
            role: 'io',
            dataType: { kind: 'object' },
            label: 'in_dest',
          },
          {
            id: 'in_source_0',
            direction: 'in',
            role: 'io',
            dataType: { kind: 'object' },
            label: 'in_source_0',
          },
        ],
        position: { x: 1108.8603351955308, y: -144.44692737430162 },
      },
    ],
    edges: [
      {
        id: 'edge-3',
        kind: 'flow',
        source: '@start',
        target: 'cmd-splitCoins-1',
        sourceHandle: 'next',
        targetHandle: 'prev',
      },
      {
        id: 'edge-7',
        kind: 'io',
        source: '@gas',
        target: 'cmd-splitCoins-1',
        sourceHandle: 'out:object',
        targetHandle: 'in_coin:object',
      },
      {
        id: 'edge-10',
        kind: 'io',
        source: 'var-9',
        target: 'cmd-splitCoins-1',
        sourceHandle: 'out:number',
        targetHandle: 'in_amount_0:number',
        cast: { to: 'u64' },
      },
      {
        id: 'edge-12',
        kind: 'flow',
        source: 'cmd-splitCoins-1',
        target: 'cmd-mergeCoins-11',
        sourceHandle: 'next',
        targetHandle: 'prev',
      },
      {
        id: 'edge-13',
        kind: 'flow',
        source: 'cmd-mergeCoins-11',
        target: '@end',
        sourceHandle: 'next',
        targetHandle: 'prev',
      },
      {
        id: 'edge-14',
        kind: 'io',
        source: 'cmd-splitCoins-1',
        target: 'cmd-mergeCoins-11',
        sourceHandle: 'out_coin_0:object',
        targetHandle: 'in_source_0:object',
      },
      {
        id: 'edge-15',
        kind: 'io',
        source: '@gas',
        target: 'cmd-mergeCoins-11',
        sourceHandle: 'out:object',
        targetHandle: 'in_dest:object',
      },
    ],
  },
  modules: {},
  objects: {},
};

export const PTBTemplate_merge: PTBTemplateItem = {
  id: 'merge',
  label: 'Merge Template',
  description: 'Sample merge pipeline',
  defaultName: 'merge.ptb',
  detail: 'Merge multiple Coins (MergeCoins).',
  file: () => JSON.stringify(mergeTemplateJson, null, 2),
};
